#----------------------------------
# Header
#
menu:
  Home: /
  Archive: /archives

rss: /atom.xml

#----------------------------------
# Footer
#

social:
  GitHub: https://github.com/Drafffffff
  Weibo: https://weibo.com/u/6863939296?is_hot=1
  Twitter: https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzUyODk3NzQyOQ==#wechat_redirect
  LinkedIn: 

#----------------------------------
# Search
#

search_title: Search
search_subtitle: Find out the treasure.
search_placeholder: Enter Keyword

#----------------------------------
# Comment
#

# fill in with your duoshuo/disqus short_name
duoshuo: 
disqus: 

#----------------------------------
# Analytics
#

# ga for google analytics
# ba for baidu analytics (百度统计)

ga: 
ba: 

#----------------------------------
# Miscellaneous
#

# author_page is your personal website url
author_page: 

home_title: Latest List
archive_title: Archive
article_breadcrumb: ITEM
page_breadcrumb: PAGE

favicon: /favicon.png

#----------------------------------
